name: Deploy Disease Diagnosis Page

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace API key placeholder
        run: |
          sed -i 's/GMAP_KEY/${{ secrets.GOOGLE_MAPS_API_KEY }}/g' project/disease-diagnosis.html

      # Add other deployment steps here
